import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Max Autolytics - Data Analytics for Dealers',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/autolytics_logo_small.ico" sizes="any" type="image/svg+xml" />
      </head>
      <body className={inter.className}>
        <Header />
        <div className='w-full aspect-square rounded-full bg-gradient-to-r from-[#F90] from-8.85% via-[#F63333] via-25% to-[#00E0FF] to-100% blur-[12rem] absolute -top-[150%] -z-50 opacity-60'></div>
        {children}
      </body>
    </html>
  )
}
